name: qself-brandur CI

on:
  pull_request:
  push:
  schedule:
    # Once every 3 hours.
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3

      - name: Install Qself
        run: go install github.com/brandur/qself@latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync all
        run: $(go env GOPATH)/bin/qself sync-all --goodreads-path data/goodreads.toml
        env:
          GOODREADS_ID: 5896508
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}

      - name: Commit and push (if changed)
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -u
          git commit -m "Automatic update from GitHub Action" || exit 0
          git push
        if: github.ref == 'refs/heads/master'
