name: qself-brandur CI

on:
  pull_request:
  push:
  schedule:
    # Once every 3 hours.
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      # Used to force dependencies to re-cache once a day so that we don't run
      # into any weird cache invalidation problems, so to make sure that
      # dependency fetches keep working.
      # - name: Get date
      #   id: get-date
      #   run: |
      #     echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d")"
      #   shell: bash

      # - name: Cache dependencies
      #   id: cache-dependencies
      #   uses: actions/cache@v2
      #   with:
          # Don't try to use variables in these paths. They don't seem to work
          # and it'll lead to hours of confusion. You can use a `~`, but I've
          # expanded HOME so that finding things is easier.
      #     path: |
      #       /home/runner/go/bin/
      #       /home/runner/go/pkg/mod/
      #     key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-cache-dependencies-v2

      - name: Install Qself
      #   if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: go get -u github.com/brandur/qself

      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync all
        run: $(go env GOPATH)/bin/qself sync-all --goodreads-path data/goodreads.toml --twitter-path data/twitter.toml
        env:
          GOODREADS_ID: 5896508
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_USER: brandur

      - name: Commit and push (if changed)
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -u
          git commit -m "Automatic update from GitHub Action" || exit 0
          git push
        if: github.ref == 'refs/heads/master'
